"""add_measurements_work_done

Revision ID: 8c4d25b031f1
Revises: 26e5a05077fd
Create Date: 2026-03-24 14:33:52.415199
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '8c4d25b031f1'
down_revision: Union[str, None] = '26e5a05077fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('measurement_no', sa.String(length=100), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False, comment='draft | submitted | approved'),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurements_contract_id'), 'measurements', ['contract_id'], unique=False)
    op.create_index(op.f('ix_measurements_id'), 'measurements', ['id'], unique=False)
    op.create_index(op.f('ix_measurements_measurement_no'), 'measurements', ['measurement_no'], unique=True)
    op.create_table('measurement_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_attachments_id'), 'measurement_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_measurement_attachments_measurement_id'), 'measurement_attachments', ['measurement_id'], unique=False)
    op.create_table('measurement_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('boq_item_id', sa.Integer(), nullable=False),
    sa.Column('description_snapshot', sa.Text(), nullable=False),
    sa.Column('unit_snapshot', sa.String(length=30), nullable=False),
    sa.Column('previous_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('cumulative_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('allow_excess', sa.Boolean(), nullable=False),
    sa.Column('warning_message', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], ),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_items_boq_item_id'), 'measurement_items', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_measurement_items_id'), 'measurement_items', ['id'], unique=False)
    op.create_index(op.f('ix_measurement_items_measurement_id'), 'measurement_items', ['measurement_id'], unique=False)
    op.create_table('work_done_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('measurement_item_id', sa.Integer(), nullable=False),
    sa.Column('boq_item_id', sa.Integer(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('previous_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('cumulative_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ),
    sa.ForeignKeyConstraint(['measurement_item_id'], ['measurement_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_done_items_boq_item_id'), 'work_done_items', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_work_done_items_contract_id'), 'work_done_items', ['contract_id'], unique=False)
    op.create_index(op.f('ix_work_done_items_id'), 'work_done_items', ['id'], unique=False)
    op.create_index(op.f('ix_work_done_items_measurement_id'), 'work_done_items', ['measurement_id'], unique=False)
    op.create_index(op.f('ix_work_done_items_measurement_item_id'), 'work_done_items', ['measurement_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_done_items_measurement_item_id'), table_name='work_done_items')
    op.drop_index(op.f('ix_work_done_items_measurement_id'), table_name='work_done_items')
    op.drop_index(op.f('ix_work_done_items_id'), table_name='work_done_items')
    op.drop_index(op.f('ix_work_done_items_contract_id'), table_name='work_done_items')
    op.drop_index(op.f('ix_work_done_items_boq_item_id'), table_name='work_done_items')
    op.drop_table('work_done_items')
    op.drop_index(op.f('ix_measurement_items_measurement_id'), table_name='measurement_items')
    op.drop_index(op.f('ix_measurement_items_id'), table_name='measurement_items')
    op.drop_index(op.f('ix_measurement_items_boq_item_id'), table_name='measurement_items')
    op.drop_table('measurement_items')
    op.drop_index(op.f('ix_measurement_attachments_measurement_id'), table_name='measurement_attachments')
    op.drop_index(op.f('ix_measurement_attachments_id'), table_name='measurement_attachments')
    op.drop_table('measurement_attachments')
    op.drop_index(op.f('ix_measurements_measurement_no'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_contract_id'), table_name='measurements')
    op.drop_table('measurements')
    # ### end Alembic commands ###
