"""add_ra_bill_workflow_states

Revision ID: d00a58ecc81c
Revises: ff78546a7f51
Create Date: 2026-03-24 15:03:30.530543
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'd00a58ecc81c'
down_revision: Union[str, None] = 'ff78546a7f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    is_sqlite = op.get_bind().dialect.name == "sqlite"
    op.create_table('ra_bill_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ra_bill_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ra_bill_id'], ['ra_bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ra_bill_status_logs_actor_user_id'), 'ra_bill_status_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_ra_bill_status_logs_id'), 'ra_bill_status_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ra_bill_status_logs_ra_bill_id'), 'ra_bill_status_logs', ['ra_bill_id'], unique=False)
    if not is_sqlite:
        op.alter_column('ra_bills', 'status',
                   existing_type=sa.VARCHAR(length=30),
                   comment='draft | submitted | verified | approved | rejected | cancelled | finance_hold | partially_paid | paid',
                   existing_comment='draft | submitted | approved | paid | rejected',
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    is_sqlite = op.get_bind().dialect.name == "sqlite"
    if not is_sqlite:
        op.alter_column('ra_bills', 'status',
                   existing_type=sa.VARCHAR(length=30),
                   comment='draft | submitted | approved | paid | rejected',
                   existing_comment='draft | submitted | verified | approved | rejected | cancelled | finance_hold | partially_paid | paid',
                   existing_nullable=False)
    op.drop_index(op.f('ix_ra_bill_status_logs_ra_bill_id'), table_name='ra_bill_status_logs')
    op.drop_index(op.f('ix_ra_bill_status_logs_id'), table_name='ra_bill_status_logs')
    op.drop_index(op.f('ix_ra_bill_status_logs_actor_user_id'), table_name='ra_bill_status_logs')
    op.drop_table('ra_bill_status_logs')
    # ### end Alembic commands ###
