"""add_secured_advances_and_payment_lifecycle

Revision ID: e135ebdf735c
Revises: e48ab6c3e0ad
Create Date: 2026-03-24 15:28:50.358522
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'e135ebdf735c'
down_revision: Union[str, None] = 'e48ab6c3e0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    is_sqlite = op.get_bind().dialect.name == "sqlite"
    op.create_table('secured_advances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('advance_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('advance_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('recovered_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False, comment='active | fully_recovered | written_off'),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secured_advances_contract_id'), 'secured_advances', ['contract_id'], unique=False)
    op.create_index(op.f('ix_secured_advances_id'), 'secured_advances', ['id'], unique=False)
    op.create_table('secured_advance_recoveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secured_advance_id', sa.Integer(), nullable=False),
    sa.Column('ra_bill_id', sa.Integer(), nullable=False),
    sa.Column('recovery_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ra_bill_id'], ['ra_bills.id'], ),
    sa.ForeignKeyConstraint(['secured_advance_id'], ['secured_advances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secured_advance_recoveries_id'), 'secured_advance_recoveries', ['id'], unique=False)
    op.create_index(op.f('ix_secured_advance_recoveries_ra_bill_id'), 'secured_advance_recoveries', ['ra_bill_id'], unique=False)
    op.create_index(op.f('ix_secured_advance_recoveries_secured_advance_id'), 'secured_advance_recoveries', ['secured_advance_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('ra_bill_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['ra_bill_id'], ['ra_bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_allocations_id'), 'payment_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_ra_bill_id'), 'payment_allocations', ['ra_bill_id'], unique=False)
    if is_sqlite:
        with op.batch_alter_table('deductions') as batch_op:
            batch_op.add_column(sa.Column('reason', sa.String(length=500), nullable=True))
            batch_op.add_column(sa.Column('secured_advance_id', sa.Integer(), nullable=True))
            batch_op.add_column(
                sa.Column(
                    'is_system_generated',
                    sa.Boolean(),
                    nullable=False,
                    server_default=sa.text('false'),
                ),
            )
            batch_op.create_foreign_key(
                'fk_deductions_secured_advance_id_secured_advances',
                'secured_advances',
                ['secured_advance_id'],
                ['id'],
            )
            batch_op.create_index(
                op.f('ix_deductions_secured_advance_id'),
                ['secured_advance_id'],
                unique=False,
            )
        with op.batch_alter_table('payments') as batch_op:
            batch_op.add_column(
                sa.Column(
                    'status',
                    sa.String(length=30),
                    nullable=False,
                    server_default='draft',
                ),
            )
            batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
            batch_op.add_column(sa.Column('released_by', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('released_at', sa.DateTime(timezone=True), nullable=True))
            batch_op.add_column(
                sa.Column(
                    'updated_at',
                    sa.DateTime(timezone=True),
                    server_default=sa.text('CURRENT_TIMESTAMP'),
                    nullable=True,
                )
            )
            batch_op.create_foreign_key(
                'fk_payments_approved_by_users',
                'users',
                ['approved_by'],
                ['id'],
            )
            batch_op.create_foreign_key(
                'fk_payments_released_by_users',
                'users',
                ['released_by'],
                ['id'],
            )
    else:
        op.add_column('deductions', sa.Column('reason', sa.String(length=500), nullable=True))
        op.add_column('deductions', sa.Column('secured_advance_id', sa.Integer(), nullable=True))
        op.add_column(
            'deductions',
            sa.Column(
                'is_system_generated',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('false'),
            ),
        )
        op.alter_column('deductions', 'deduction_type',
                   existing_type=sa.VARCHAR(length=50),
                   comment='tds | retention | penalty | previous_adjustment | manual | secured_advance_recovery',
                   existing_comment='tds | retention | security_deposit | penalty | other',
                   existing_nullable=False)
        op.create_index(op.f('ix_deductions_secured_advance_id'), 'deductions', ['secured_advance_id'], unique=False)
        op.create_foreign_key(None, 'deductions', 'secured_advances', ['secured_advance_id'], ['id'])
        op.add_column(
            'payments',
            sa.Column(
                'status',
                sa.String(length=30),
                nullable=False,
                server_default='draft',
                comment='draft | approved | released | cancelled',
            ),
        )
        op.add_column('payments', sa.Column('approved_by', sa.Integer(), nullable=True))
        op.add_column('payments', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        op.add_column('payments', sa.Column('released_by', sa.Integer(), nullable=True))
        op.add_column('payments', sa.Column('released_at', sa.DateTime(timezone=True), nullable=True))
        op.add_column('payments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        op.create_foreign_key(None, 'payments', 'users', ['approved_by'], ['id'])
        op.create_foreign_key(None, 'payments', 'users', ['released_by'], ['id'])
    op.create_index(op.f('ix_payments_contract_id'), 'payments', ['contract_id'], unique=False)
    op.create_index(op.f('ix_payments_ra_bill_id'), 'payments', ['ra_bill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    is_sqlite = op.get_bind().dialect.name == "sqlite"
    op.drop_index(op.f('ix_payments_ra_bill_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_contract_id'), table_name='payments')
    if is_sqlite:
        with op.batch_alter_table('payments') as batch_op:
            batch_op.drop_constraint('fk_payments_released_by_users', type_='foreignkey')
            batch_op.drop_constraint('fk_payments_approved_by_users', type_='foreignkey')
            batch_op.drop_column('updated_at')
            batch_op.drop_column('released_at')
            batch_op.drop_column('released_by')
            batch_op.drop_column('approved_at')
            batch_op.drop_column('approved_by')
            batch_op.drop_column('status')
        with op.batch_alter_table('deductions') as batch_op:
            batch_op.drop_constraint(
                'fk_deductions_secured_advance_id_secured_advances',
                type_='foreignkey',
            )
            batch_op.drop_index(op.f('ix_deductions_secured_advance_id'))
            batch_op.drop_column('is_system_generated')
            batch_op.drop_column('secured_advance_id')
            batch_op.drop_column('reason')
    else:
        op.drop_constraint(None, 'payments', type_='foreignkey')
        op.drop_constraint(None, 'payments', type_='foreignkey')
        op.drop_column('payments', 'updated_at')
        op.drop_column('payments', 'released_at')
        op.drop_column('payments', 'released_by')
        op.drop_column('payments', 'approved_at')
        op.drop_column('payments', 'approved_by')
        op.drop_column('payments', 'status')
        op.drop_constraint(None, 'deductions', type_='foreignkey')
        op.drop_index(op.f('ix_deductions_secured_advance_id'), table_name='deductions')
        op.alter_column('deductions', 'deduction_type',
                   existing_type=sa.VARCHAR(length=50),
                   comment='tds | retention | security_deposit | penalty | other',
                   existing_comment='tds | retention | penalty | previous_adjustment | manual | secured_advance_recovery',
                   existing_nullable=False)
        op.drop_column('deductions', 'is_system_generated')
        op.drop_column('deductions', 'secured_advance_id')
        op.drop_column('deductions', 'reason')
    op.drop_index(op.f('ix_payment_allocations_ra_bill_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_secured_advance_recoveries_secured_advance_id'), table_name='secured_advance_recoveries')
    op.drop_index(op.f('ix_secured_advance_recoveries_ra_bill_id'), table_name='secured_advance_recoveries')
    op.drop_index(op.f('ix_secured_advance_recoveries_id'), table_name='secured_advance_recoveries')
    op.drop_table('secured_advance_recoveries')
    op.drop_index(op.f('ix_secured_advances_id'), table_name='secured_advances')
    op.drop_index(op.f('ix_secured_advances_contract_id'), table_name='secured_advances')
    op.drop_table('secured_advances')
    # ### end Alembic commands ###
