"""allow_rebill_after_rejection

Revision ID: e48ab6c3e0ad
Revises: 9702fcae2bed
Create Date: 2026-03-24 15:14:17.403522
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'e48ab6c3e0ad'
down_revision: Union[str, None] = '9702fcae2bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ra_bill_items_work_done_item_id', table_name='ra_bill_items')
    op.create_index(op.f('ix_ra_bill_items_work_done_item_id'), 'ra_bill_items', ['work_done_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ra_bill_items_work_done_item_id'), table_name='ra_bill_items')
    op.create_index('ix_ra_bill_items_work_done_item_id', 'ra_bill_items', ['work_done_item_id'], unique=True)
    # ### end Alembic commands ###
