"""add_ra_bill_mvp

Revision ID: ff78546a7f51
Revises: 8c4d25b031f1
Create Date: 2026-03-24 14:48:36.962428
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'ff78546a7f51'
down_revision: Union[str, None] = '8c4d25b031f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ra_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('bill_no', sa.Integer(), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_payable', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False, comment='draft | submitted | approved | paid | rejected'),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'bill_no', name='uq_ra_bills_contract_bill_no')
    )
    op.create_index(op.f('ix_ra_bills_bill_no'), 'ra_bills', ['bill_no'], unique=False)
    op.create_index(op.f('ix_ra_bills_contract_id'), 'ra_bills', ['contract_id'], unique=False)
    op.create_index(op.f('ix_ra_bills_id'), 'ra_bills', ['id'], unique=False)
    op.create_table('deductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ra_bill_id', sa.Integer(), nullable=False),
    sa.Column('deduction_type', sa.String(length=50), nullable=False, comment='tds | retention | security_deposit | penalty | other'),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['ra_bill_id'], ['ra_bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deductions_id'), 'deductions', ['id'], unique=False)
    op.create_index(op.f('ix_deductions_ra_bill_id'), 'deductions', ['ra_bill_id'], unique=False)
    op.create_table('ra_bill_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ra_bill_id', sa.Integer(), nullable=False),
    sa.Column('work_done_item_id', sa.Integer(), nullable=False),
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('boq_item_id', sa.Integer(), nullable=False),
    sa.Column('item_code_snapshot', sa.String(length=50), nullable=True),
    sa.Column('description_snapshot', sa.Text(), nullable=False),
    sa.Column('unit_snapshot', sa.String(length=30), nullable=False),
    sa.Column('prev_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('curr_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('cumulative_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], ),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ),
    sa.ForeignKeyConstraint(['ra_bill_id'], ['ra_bills.id'], ),
    sa.ForeignKeyConstraint(['work_done_item_id'], ['work_done_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ra_bill_items_boq_item_id'), 'ra_bill_items', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_ra_bill_items_id'), 'ra_bill_items', ['id'], unique=False)
    op.create_index(op.f('ix_ra_bill_items_measurement_id'), 'ra_bill_items', ['measurement_id'], unique=False)
    op.create_index(op.f('ix_ra_bill_items_ra_bill_id'), 'ra_bill_items', ['ra_bill_id'], unique=False)
    op.create_index(op.f('ix_ra_bill_items_work_done_item_id'), 'ra_bill_items', ['work_done_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ra_bill_items_work_done_item_id'), table_name='ra_bill_items')
    op.drop_index(op.f('ix_ra_bill_items_ra_bill_id'), table_name='ra_bill_items')
    op.drop_index(op.f('ix_ra_bill_items_measurement_id'), table_name='ra_bill_items')
    op.drop_index(op.f('ix_ra_bill_items_id'), table_name='ra_bill_items')
    op.drop_index(op.f('ix_ra_bill_items_boq_item_id'), table_name='ra_bill_items')
    op.drop_table('ra_bill_items')
    op.drop_index(op.f('ix_deductions_ra_bill_id'), table_name='deductions')
    op.drop_index(op.f('ix_deductions_id'), table_name='deductions')
    op.drop_table('deductions')
    op.drop_index(op.f('ix_ra_bills_id'), table_name='ra_bills')
    op.drop_index(op.f('ix_ra_bills_contract_id'), table_name='ra_bills')
    op.drop_index(op.f('ix_ra_bills_bill_no'), table_name='ra_bills')
    op.drop_table('ra_bills')
    # ### end Alembic commands ###
